# Generated by Django 6.0.6 on 2026-09-07
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("commerce", "0002_order_payment_and_shipping")]

    operations = [
        migrations.AddField(
            model_name="wishlistitem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="wishlistitem",
            name="wishlist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="commerce.wishlist",
            ),
        ),
    ]
