from django.urls import path
from .views import (
    AcceptDeliveryView,
    AcceptReturnView,
    CancelOrderItemView,
    CancelOrderView,
    CartView,
    CartItemDetailView,
    CheckoutView,
    CouponListView,
    DeliveryOrdersListView,
    InvoiceView,
    OrderDetailView,
    OrderListView,
    PayUCallbackView,
    PayUInitiateView,
    ReturnOrderItemView,
    ReturnOrderView,
    UpdateOrderStatusView,
    ValidateCouponView,
    WishlistView,
    WishlistItemDetailView,
)

urlpatterns = [
    path("cart/", CartView.as_view(), name="cart"),
    path("cart/items/<int:item_id>/", CartItemDetailView.as_view(), name="cart_item_detail"),
    path("wishlist/", WishlistView.as_view(), name="wishlist"),
    path("wishlist/items/<int:item_id>/", WishlistItemDetailView.as_view(), name="wishlist_item_detail"),
    path("coupons/", CouponListView.as_view(), name="coupon_list"),
    path("coupons/validate/", ValidateCouponView.as_view(), name="validate_coupon"),
    path("checkout/", CheckoutView.as_view(), name="checkout"),
    path("payments/payu/initiate/", PayUInitiateView.as_view(), name="payu_initiate"),
    path("payments/payu/callback/", PayUCallbackView.as_view(), name="payu_callback"),
    path("orders/", OrderListView.as_view(), name="order_list"),
    path("orders/deliveries/", DeliveryOrdersListView.as_view(), name="delivery_orders_list"),
    path("orders/<int:order_id>/", OrderDetailView.as_view(), name="order_detail"),
    path("orders/<int:order_id>/invoice/", InvoiceView.as_view(), name="order_invoice"),
    path("orders/<int:order_id>/cancel/", CancelOrderView.as_view(), name="cancel_order"),
    path("orders/<int:order_id>/items/<int:item_id>/cancel/", CancelOrderItemView.as_view(), name="cancel_order_item"),
    path("orders/<int:order_id>/return/", ReturnOrderView.as_view(), name="return_order"),
    path("orders/<int:order_id>/items/<int:item_id>/return/", ReturnOrderItemView.as_view(), name="return_order_item"),
    path("orders/<int:order_id>/accept_delivery/", AcceptDeliveryView.as_view(), name="accept_delivery"),
    path("orders/<int:order_id>/accept_return/", AcceptReturnView.as_view(), name="accept_return"),
    path("orders/<int:order_id>/status/", UpdateOrderStatusView.as_view(), name="update_order_status"),
]
