# Generated by Django 6.0.6 on 2026-09-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_reconcile_legacy_catalog_table_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('image_url', models.CharField(max_length=500)),
                ('target_category', models.CharField(blank=True, max_length=100)),
                ('target_url', models.CharField(blank=True, max_length=500)),
                ('button_text', models.CharField(default='Shop Now', max_length=50)),
                ('badge', models.CharField(default='Exclusive Offer', max_length=50)),
                ('bg_gradient', models.CharField(blank=True, default='from-slate-950 via-indigo-950 to-blue-900', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'banners',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
